### ISSUE TITLE
[Feature Request] UI tweaking

### ISSUE THREAD

**Issue by MulverineX** [Rodentman87/reddit-parser#5]
Currently, the profile image looks kinda haphazardly injected into the markup, I think to make the design more fluid you should make a custom component for the user/subreddit mention with a background (either a different bg var than channel or the mention highlight), a bit of padding on the left/right, and vertically centered text (on the icon).

**Comment by Rodentman87** [comment]
The current design was a deliberate choice as it more closely matches the formatting in the reddit app, some people asked for a toggle to make it render like a mention, which I added. I'm not quite sure what you're asking for beyond that.

**Comment by MulverineX** [comment]
Oh lol, I should've looked at settings first, maybe that should be by default though since this *is* discord and not reddit.

**Comment by Rodentman87** [comment]
Should be on by default I think? The only setting off by default is displaying NSFW icons.

**Comment by MulverineX** [comment]
![image](https://user-images.githubusercontent.com/12068027/98703055-5704b880-2338-11eb-8ffe-e6ba811be5e4.png)
looks like I do have the mention rendering, my feedback was for this.

**Comment by MulverineX** [comment]
This is just a link with an image posted to its left, its not stylized like a mention at all

**Comment by Rodentman87** [comment]
That's not the mention style rendering, check your settings for the plug-in. It uses the default mention css class so that it aligns with any changes your theme might make.

**Comment by MulverineX** [comment]
![image](https://user-images.githubusercontent.com/12068027/98703803-28d3a880-2339-11eb-909b-a0d73ee3f7bd.png)

**Comment by MulverineX** [comment]
(this is with my themes disabled and I toggled the mention highlighting off and on and switched channels)

**Comment by MulverineX** [comment]
I know that the settings are working partially too because the icon toggle works

**Comment by Rodentman87** [comment]
Just pushed out a fix to the mention rendering there.
